### PR TITLE
test-upload.txt file is now uploaded in the uploads folder

### PR DESCRIPTION
**Pull request by TehSebaXx**
Now even if you fail some tests the "test-upload.txt" will be ignored by git since is in the uploads folder

### CODE REVIEW

**Comment by JesseRWeigel** [comment]
Thanks @TehSebaXx !

**Comment by kebien6020** [comment]
But that kind of defeats the purpose because you create a file in the uploads folder and then when you upload the file it replaces itself. So you wouldn't know if the test passed or not.

Maybe use [temp](https://www.npmjs.com/package/temp) or [tmp](https://www.npmjs.com/package/tmp) or something like that to create the temporary file in a suitable temp folder.

Or use a try ... finally around the await page ... end() and in the finally block dispose of the files (unlinkSync works even if the file does not exist).

**Comment by TehSebaXx** [comment]
So there were 2 files created? Never noticed...

**Comment by kebien6020** [comment]
Yes, the second file exists for a second and then when the test checks that its there it deletes both files. The file in the /uploads folder is created by the server itself.

**Comment by TehSebaXx** [comment]
hmmm... but why have 2? I understand the one in the uploads folder but other one I don't get it...

**Comment by kebien6020** [comment]
This test is similar to creating a file in your computer with some content in it, hitting the "upload files" button in the form and adding that file, then hitting submit.

Now there are 2 files: one in your computer and one in the server's upload folder. If you want to be sure that the upload worked you compare the contents of both files and they should be the same.

Once you confirm that, you delete both files. The temporary you created to do the testing and the one in the server's uploads folder that was not directly created by you.

**Comment by JesseRWeigel** [comment]
I reverted back to the original way of handling this, but I added test-upload.txt to the .gitignore file. ( 6dc6983  ). This will at least prevent it from getting committed.

**Comment by TehSebaXx** [comment]
@kebien6020 Ok, now I understood it! Thanks for clarifying!

**Pull request merged**
