### PR TITLE
Adjust stateless components, fix Logos.js warning, fix lint errors, and add sass-loader 

### PR DESCRIPTION
**Pull request by mattcarlotta**
Changes include:
- If a component doesn't utilize state nor alter props, then it was changed to a stateless fat arrow function
- Adjusted components to initialize state in the class constructor
- Fix Logo.js key warning, where line 109 was missing a key={tabKey} parameter
- Fix multiple lint errors -- most deriving from fat arrow functions placed outside the render method and undefined inside the React component class object.
- Revamped the styles folder. In short, uncoupled the create-react-app and added sass-loader to Webpack in order to load a single styles.scss file that imports all stylesheets/variables for you and shares them across all components. See the [styles.css](https://github.com/mattcarlotta/resource-center/blob/master/src/styles/styles.scss) notes for more information on how to add new files/stylesheets/variables. Saving scss files still triggers auto freshes!**

** Important note: Uncoupling the create-react-app by running "npm run eject," moves the config and script files outside of the nodemodules folder and into the app's root directory. This essentially creates a custom app and breaks the purpose of a simple hands off create-react-app, however, DOES NOT break its functionality. Also, since adding sass-loader, I removed "watch css," from the package.json "start" up script. This makes it so that styles.scss file will no longer compile to styles.css. For a dev environment, this is not necessary nor beneficial in start-up performance.

### CODE REVIEW

**Comment by mattcarlotta** [comment]
Missed the stream, but I'll clarify a few things:
1. According the React docs, state should be initialized in the class constructor or in ComponentDidMount from an AJAX request. Setting state directly is anti-pattern (see below). This may have changed with the new syntax/new updates, but from what I've been learned/read **so far** is that you should avoid setting state directly. For example this would be mutating state:
`  state = {
    activeTab: 'all',
    data: logos,
    type: 'all'
  } 
`

**Setting state properly:** 
Using this.setState: https://facebook.github.io/react/docs/state-and-lifecycle.html#using-state-correctly
Initializing class state: https://facebook.github.io/react/docs/state-and-lifecycle.html#adding-local-state-to-a-class
https://facebook.github.io/react-native/docs/state.html

**Performance optimizations** (scroll down to "The Power Of Not Mutating Data"):  https://facebook.github.io/react/docs/optimizing-performance.html

2. It could just be an outdated linter you're using that's causing those fat arrow function errors. But, if you don't want to change the linter/disable it, then you can still utilize es6+ syntax by simply moving the fat arrow function inside the render method (just note that you're no longer using "this.handleChange," but instead just "handleChange" to call the function):

```
class Logos extends Component {
  constructor (props) {
    super(props)

    this.state = {
      activeTab: 'all',
      data: logos,
      type: 'all'
    }
  }
  
   render () {
    ...
    const handleChange = (event, index, value) => {
      this.setState({ activeTab: value })
    }
    ...
      return (
              ...
             <SelectField
              floatingLabelText='Logo Type'
              value={this.state.activeTab}
              onChange={handleChange}
              style={{ textAlign: 'left' }}
            >
             ...
      )
   }
}
```
I prefer to use normal functions inside the class object and outside of the render method. However, if I'm using a stateless component, then I'll only use fat arrow functions (personal preference). I haven't noticed any performance gains/deficiencies using either the "old" or "new" method:

```
import React from 'react';

export const Title = (props) => {
  const showTitle = () => {
   if (props.blogIsLoaded) return <h1>Blog<h1>
   return <h1>Home<h1>
  }

  return (
    <div className="index-container">
      { showTitle() }
    </div>
  )
}
```

3. The revamped style loading is pretty simple to use. It's basically a single styles file that is importing all of the smaller styled component files for you. And that single file is imported at the App level. So if you want to share some styles from different scss components, you won't need to import individual scss files nor individual classes. Instead they're already shared. So you could, in bad practice, add a css class to "_logos.scss" and then utilize that css class in "Home.js". In, good practice, you could add a variable to "_component_variables.scss" and utilize that variable in multiple component style sheets without having to import the variables over and over again. Or, in good practice, `@extend` a css class from one style file to another style file without having to importing anything. This will make your stylesheets more flexible and less tedious to utilize across newly created and/or already established components.

**Comment by mattcarlotta** [comment]
Small update: About setting state, not sure if this becoming the norm or is lazy code, but this is the first time I've seen it set like `state = {}`:

If you view the code for "Customized Validation", you'll see state set similar to above, but if you look at their other forms, like "Form Layout," state is initiated through the constructor class: https://ant.design/components/form/

**Comment by JesseRWeigel** [comment]
@mattcarlotta thank you for explaining all of this to me. I understand the changes much better now. I really like the features available by loading sass in this way. 

I will probably end up merging this in at some point, but I will need to take some time to fix the merge conflicts since so much has changed since this PR was created.

**Comment by mattcarlotta** [comment]
Sounds good. If you haven't already, clone the [fork](https://github.com/mattcarlotta/resource-center) and test it out. If you don't like the flow, one of us can close this pull request and I can do a smaller (if necessary) pull request minus the sass-loader.

**Comment by mattcarlotta** [comment]
Important note: Due to the way the Linter is set up for this particular app, you will get errors regarding importing anything (stylesheets for example) placed outside of the src folder (nodemodules imports are OK). You can do the following to fix these Linter issues:
1. Move the stylesheets into the src folder and then adjust the import path in styles.scss, for example:
`@import "/src/assets/font-awesome/css/font-awesome.min.css";`
2. Load the stylesheets from the index.html, for example under `<head>`:
`<link rel="stylesheet" type="text/css" href="%PUBLIC_URL%/assets/font-awesome/css/font-awesome.min.css">` (in a dev env, `%PUBLIC_URL%` would be: `directory/to/appfolder/public`)
3. Use a CDN in index.html.

In this case, I'd recommend option 2. Less work for the sass-loader.

**Pull request closed without merging**
