### PR TITLE
Refactor GenericCard

### PR DESCRIPTION
**Pull request by planigan**
Simple refactoring similar to others I have submitted.

### CODE REVIEW

**Comment by planigan** [comment]
Changes:
* I moved the repeated `JSX` into the functional stateless local component `CardContent`
* I pulled in `debounce` from lodash which is provided with CRA and used it to debounce the mouse handlers.
* I checked to see if `setState` would actually change the state before calling so as to not mark the component dirty unnecessarily.
* I added a `target='_blank'` to external links. Wasn't sure if you wanted that, but the internal and external links are separate now, so, you have the option.

Note: I removed `isExact` from the `Link` because it was throwing an error in the console and seems to work as expected without it. Do test that to make sure it has your intended behavior.

**Comment by TehSebaXx** [comment]
> Note: I removed isExact from the Link because it was throwing an error in the console and seems to work as expected without it. Do test that to make sure it has your intended behavior.
That's because `isExact` should be passed as a prop as a boolean, then used in `<Link>` as `<Link to='/path' exact={isExact}` which translated to `exact=true/false`. Check the `SideNav.js` and `SideBarItem.js` to see how I used it.

**Comment by TehSebaXx** [comment]
Suggestion:
 - Make the entire card a link by nesting the `<Paper>` components inside the `<Link>` component.

As it is right now the `<Link>` area depends on how much text is in the card and the width and height, the rest is not clickable.

screenshot from 2017-08-15 16-30-49

**Comment by planigan** [comment]
Good call @TehSebaXx on the paper needing to be inside the link. I'll refactor it into `CardContent` this afternoon and update the PR.

**Comment by planigan** [comment]
Changes in the latest commit:
* Pull `Paper` into `CardContent` so as to make entire card clickable when it's a link.
* Alphabetize the parameters of `CardContent` because it's long and my OCD kicked in :smiling_imp:

**Comment by JesseRWeigel** [comment]
Thank you @planigan !

Great catch on the link area @TehSebaXx

**Pull request merged**
